@extends('layouts.app')

@section('title', config('app.name'))
@section('description', 'Astrology Webinar - Your platform for webinars and live events.')

@section('content')
    @include('pages.astrology.sections.Astro-hero-section', ['ctaHref' => url('/astrology-checkout')])
    @include('pages.astrology.sections.Astro-featured-in')
    @include('pages.astrology.sections.Astro-what-is-astrology')
    @include('pages.astrology.sections.Astro-what-you-will-learn')
    @include('pages.astrology.sections.Astro-how-graphology-works', ['bonusCtaHref' => url('/astrology-checkout')])
    @include('pages.astrology.sections.Astro-certificate-section', ['ctaHref' => url('/astrology-checkout')])
    @include('pages.astrology.sections.Astro-workshop-snapshots', ['images' => ['images/12.webp', 'images/13.webp']])
    @include('pages.astrology.sections.Astro-graphology-steps')
    @include('pages.astrology.sections.Astro-who-uses-graphology')
    @include('pages.astrology.sections.Astro-video-testimonials')
    @include('pages.astrology.sections.Astro-about-institute')
    @include('pages.astrology.sections.Astro-meet-trainer', ['ctaHref' => url('/astrology-checkout')])
    @include('pages.astrology.sections.Astro-certified-graphologist')
    @include('pages.astrology.sections.Astro-news-article')
    @include('pages.astrology.sections.Astro-testimonials')
    @include('pages.astrology.sections.Astro-value-stack', ['ctaHref' => url('/astrology-checkout')])
    @include('pages.astrology.sections.Astro-faq')
    @include('pages.astrology.sections.Astro-end-section', ['ctaHref' => url('/astrology-checkout')])
    @include('pages.astrology.sections.Astro-sticky-bar', ['ctaHref' => url('/astrology-checkout')])
@endsection
