@extends('layouts.app')

@section('title', config('app.name'))
@section('description', 'Graphology Webinar - Your platform for webinars and live events.')

@section('content')
    @include('pages.graphology.Section-G1.Grapho-hero-section', ['ctaHref' => url('/graphology-checkout')])
    @include('pages.graphology.Section-G1.Grapho-featured-in')
    @include('pages.graphology.Section-G1.Grapho-what-is-astrology')
    @include('pages.graphology.Section-G1.Grapho-why-this-happens')
    @include('pages.graphology.Section-G1.Grapho-bonus')
    @include('pages.graphology.Section-G1.Grapho-testimonials')
    @include('pages.graphology.Section-G1.Grapho-what-you-will-learn')
    @include('pages.graphology.Section-G1.Grapho-workshop-snapshots')
    @include('pages.graphology.Section-G1.Grapho-who-uses-graphology')
    @include('pages.graphology.Section-G1.Grapho-certificate-section', ['ctaHref' => url('/graphology-checkout')])
    @include('pages.graphology.Section-G1.Grapho-video-testimonials')
    @include('pages.graphology.Section-G1.Grapho-meet-trainer', ['ctaHref' => url('/graphology-checkout')])
    @include('pages.graphology.Section-G1.Grapho-certified-graphologist')
    @include('pages.graphology.Section-G1.Grapho-text-testimonials')
    @include('pages.graphology.Section-G1.Grapho-convocation')
    @include('pages.graphology.Section-G1.Grapho-about-institute')
    @include('pages.graphology.Section-G1.Grapho-podcast')
    @include('pages.graphology.Section-G1.Grapho-faq')
    @include('pages.graphology.Section-G1.Grapho-end-section', ['ctaHref' => url('/graphology-checkout')])
    @include('pages.graphology.Section-G1.Grapho-sticky-bar', ['ctaHref' => url('/graphology-checkout')])
@endsection
